---
- hosts: departure
  become: true

  roles:
    - role: system
    - role: geerlingguy.security
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: docker/homer
    - role: docker/cup
    - role: docker/openbooks
    - role: docker/cwa
