---
- name: "Homer - Create directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - "{{ homer.volumes.root }}"
    - "{{ homer.volumes.assets }}"

- name: "Homer - Create docker-compose.yml file"
  ansible.builtin.template:
    src: "{{ homer.templates }}/docker-compose.yml.j2"
    dest: "{{ homer.volumes.root }}/docker-compose.yml"
    mode: "0644"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: "Homer - Copy assets"
  ansible.builtin.copy:
    src: "{{ homer.files }}/assets"
    dest: "{{ homer.volumes.root }}"
    mode: "0644"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: "Homer - Start containers"
  community.docker.docker_compose_v2:
    project_src: "{{ homer.volumes.root }}"
    files:
      - docker-compose.yml
